name: nihon
description: A new Flutter project.

version: 1.1.0+2 # 编译不同版本时version要改成 versionName+versionCode

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_circular_chart: ^0.1.0
  event_bus: ^1.0.1
  shared_preferences: ^0.4.1
  image_picker_saver: ^0.1.0
  esys_flutter_share: ^0.0.8
  sensors: ^0.4.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Mincho
      fonts:
        - asset: fonts/A-OTF-A1MinchoStd-Bold.otf

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
