name: nihon
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  swipedetector: ^1.2.0
  flutter_circular_chart: ^0.1.0
  event_bus: ^1.0.1
  shared_preferences: ^0.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/images/branch.png

  fonts:
    - family: Mincho
      fonts:
        - asset: fonts/A-OTF-A1MinchoStd-Bold.otf

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
